# Generated by Django 4.2 on 2023-05-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profilepage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
