# Generated by Django 4.2 on 2023-05-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profilepage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
